// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkpibMZvTIGC1iUTEk02mEYHbcTfBhJPE',
    appId: '1:408500649517:web:3217c8e44ef58ab85842a4',
    messagingSenderId: '408500649517',
    projectId: 'final-1-d33da',
    authDomain: 'final-1-d33da.firebaseapp.com',
    storageBucket: 'final-1-d33da.firebasestorage.app',
    measurementId: 'G-LVS758DNDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoFISN07utxzBuxJlT3tCEAMe5Ee6oWLw',
    appId: '1:408500649517:android:b983e6700b8182455842a4',
    messagingSenderId: '408500649517',
    projectId: 'final-1-d33da',
    storageBucket: 'final-1-d33da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCecieFS_jwksOLlSAZu2hpaFPvFL3r98M',
    appId: '1:408500649517:ios:95fa432fa10dc64d5842a4',
    messagingSenderId: '408500649517',
    projectId: 'final-1-d33da',
    storageBucket: 'final-1-d33da.firebasestorage.app',
    iosBundleId: 'com.example.finalPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCecieFS_jwksOLlSAZu2hpaFPvFL3r98M',
    appId: '1:408500649517:ios:95fa432fa10dc64d5842a4',
    messagingSenderId: '408500649517',
    projectId: 'final-1-d33da',
    storageBucket: 'final-1-d33da.firebasestorage.app',
    iosBundleId: 'com.example.finalPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkpibMZvTIGC1iUTEk02mEYHbcTfBhJPE',
    appId: '1:408500649517:web:761d1d987b50d3955842a4',
    messagingSenderId: '408500649517',
    projectId: 'final-1-d33da',
    authDomain: 'final-1-d33da.firebaseapp.com',
    storageBucket: 'final-1-d33da.firebasestorage.app',
    measurementId: 'G-41KS6JN7CZ',
  );
}
